from datetime import datetime

def export_results(tool_name, target, results):
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"osint_{tool_name}_{target}_{timestamp}.txt"
    filename = filename.replace("/", "-").replace("@", "_")

    with open(filename, "w") as f:
        f.write("=" * 50 + "\n")
        f.write(f"  OSINT Intelligence Tool — Export\n")
        f.write("=" * 50 + "\n")
        f.write(f"  Tool     : {tool_name}\n")
        f.write(f"  Target   : {target}\n")
        f.write(f"  Date     : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write("=" * 50 + "\n\n")
        f.write(results)
        f.write("\n\n// Generated by OSINT Intelligence Tool\n")

    print(f"\n  ✅ Results saved to: {filename}")
    return filename
